# Generated by Django 4.2.20 on 2025-03-23 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="gift_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="will_gift",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="wish",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
