name: Django CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Write secrets to .env
        run: |
            echo "${{ secrets.ENV_DATA }}" > .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black code formatter check
        run: |
          black . --check

      - name: Set up Docker Compose
        run: docker compose build

      - name: Run coverage tests inside Docker
        run: |
          docker compose run --rm web sh -c "
            coverage run manage.py test &&
            coverage report --fail-under=80
          "

      - name: Generate HTML coverage report
        run: docker compose run --rm web coverage html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/
